# Generated by Django 5.2.8 on 2025-11-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='LOGICIEL INTELLIGENT NOUVELLE GÉNÉRATION', max_length=255)),
                ('title_part1', models.CharField(default='Révolutionnez', help_text='Texte en couleur (classe .text-gradient)', max_length=255)),
                ('title_part2', models.CharField(default='votre gestion BTP & Architecture', max_length=255)),
                ('description', models.TextField(default="Aude combine algorithmes avancés et expertise métier pour vous offrir la solution la plus innovante du marché. Simplifiez vos projets, optimisez vos coûts et transformez votre façon de travailler dès aujourd'hui.")),
                ('primary_button_text', models.CharField(default='Démarrer mon essai gratuit', max_length=255)),
                ('primary_button_url', models.URLField(default='https://app.aude.ci')),
                ('secondary_button_text', models.CharField(default='Découvrir Aude', max_length=255)),
                ('secondary_button_modal_target', models.CharField(default='#videoModal', help_text='ID du modal Bootstrap', max_length=255)),
                ('image', models.ImageField(blank=True, default='hero/default.png', null=True, upload_to='hero/')),
            ],
            options={
                'verbose_name': 'Section Hero',
                'verbose_name_plural': 'Section Hero',
            },
        ),
    ]
