# Generated by Django 5.2.8 on 2025-11-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Ex: 15, 30, 24/7, 0€', max_length=50)),
                ('label', models.CharField(help_text="Intitulé de la statistique (ex: Jours d'essai gratuit)", max_length=255)),
                ('animation_delay', models.DecimalField(decimal_places=1, default=0.0, help_text='Ex: 0, 0.1, 0.2', max_digits=3)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ('order',),
            },
        ),
    ]
