# Generated by Django 5.2.8 on 2025-11-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_statitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statitem',
            name='animation_delay',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='statitem',
            name='label',
            field=models.CharField(default='Nouvelle statistique', max_length=255),
        ),
        migrations.AlterField(
            model_name='statitem',
            name='number',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='statitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
