# Generated by Django 5.2.8 on 2025-11-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_statitem_animation_delay_alter_statitem_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi bi-lightning-charge-fill', max_length=100)),
                ('icon_color', models.CharField(default='#fbbf24', max_length=20)),
                ('title', models.CharField(default='Nouvel avantage', max_length=255)),
                ('description', models.TextField(default='Description de l’avantage.')),
                ('footer_text', models.CharField(default='', max_length=255)),
                ('animation_delay', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Avantage',
                'verbose_name_plural': 'Avantages',
                'ordering': ('order',),
            },
        ),
    ]
