# Generated by Django 5.2.8 on 2025-11-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_advantageitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Prêt à Révolutionner Votre Gestion BTP ?', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='Rejoignez plus de 2500 professionnels qui ont déjà transformé leur business avec Aude. Démarrez votre essai gratuit dès maintenant !', null=True)),
                ('primary_button_text', models.CharField(default='Commencer gratuitement', max_length=100)),
                ('primary_button_url', models.URLField(default='https://app.aude.ci')),
                ('secondary_button_text', models.CharField(blank=True, default='Demander une démo', max_length=100, null=True)),
                ('secondary_button_url', models.URLField(blank=True, default='https://aude.ci/contact', null=True)),
                ('badge_1', models.CharField(blank=True, default='30 jours gratuits', max_length=100, null=True)),
                ('badge_2', models.CharField(blank=True, default='Sans engagement', max_length=100, null=True)),
                ('badge_3', models.CharField(blank=True, default='Support inclus', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
