# Generated by Django 5.2.8 on 2025-11-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_calltoaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Prêt à Rejoindre l'Aventure Aude ?", max_length=255)),
                ('subtitle', models.TextField(default='Découvrez comment Aude peut transformer votre façon de travailler...')),
                ('primary_button_text', models.CharField(default='Commencer gratuitement', max_length=100)),
                ('primary_button_url', models.URLField(default='https://app.aude.ci')),
                ('secondary_button_text', models.CharField(default='Nous contacter', max_length=100)),
                ('secondary_button_url', models.URLField(default='https://aude.ci/contact')),
                ('badge_1', models.CharField(default='30 jours gratuits', max_length=100)),
                ('badge_2', models.CharField(default='Sans engagement', max_length=100)),
                ('badge_3', models.CharField(default='Support dédié', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Au Cœur d'Aude : Notre Mission et Nos Valeurs", max_length=255)),
                ('subtitle', models.TextField(default="Animés par la passion de l'innovation et une compréhension profonde des défis du BTP...")),
                ('story_title', models.CharField(default='Notre Histoire : Née des Défis du Terrain', max_length=255)),
                ('story_text', models.TextField(default="Aude est le fruit d'une ambition : transformer radicalement la manière...")),
                ('vision_title', models.CharField(default="Notre Vision : L'Humain Augmenté par la Technologie", max_length=255)),
                ('vision_text', models.TextField(default="Nous croyons fermement que la technologie doit servir l'humain...")),
                ('button_text', models.CharField(default='Discutons de vos projets', max_length=100)),
                ('button_url', models.URLField(default='https://aude.ci/contact')),
                ('image', models.ImageField(default='about/apropos1.png', upload_to='about/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi-lightbulb-fill', max_length=100)),
                ('title', models.CharField(default='Innovation Continue', max_length=255)),
                ('text', models.TextField(default='Anticiper vos besoins futurs avec des technologies de pointe.')),
                ('accent_color', models.CharField(default='var(--accent-secondary)', max_length=50)),
                ('animation_delay', models.DecimalField(decimal_places=1, default=0.3, max_digits=3)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='2500', max_length=50)),
                ('label', models.CharField(default='Professionnels utilisateurs', max_length=255)),
                ('animation_delay', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
