# Generated by Django 5.2.8 on 2025-11-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_aboutcta_abouthero_aboutpillar_aboutstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionAudienceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(help_text='Bootstrap Icon ex: bi bi-buildings', max_length=100)),
                ('description', models.TextField()),
                ('badge_1', models.CharField(blank=True, max_length=100, null=True)),
                ('badge_2', models.CharField(blank=True, max_length=100, null=True)),
                ('badge_3', models.CharField(blank=True, max_length=100, null=True)),
                ('bullet_1', models.CharField(blank=True, max_length=255, null=True)),
                ('bullet_2', models.CharField(blank=True, max_length=255, null=True)),
                ('bullet_3', models.CharField(blank=True, max_length=255, null=True)),
                ('bullet_4', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SolutionCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=500)),
                ('primary_text', models.CharField(max_length=100)),
                ('primary_url', models.URLField()),
                ('secondary_text', models.CharField(max_length=100)),
                ('secondary_url', models.URLField()),
                ('highlight_1', models.CharField(blank=True, max_length=150, null=True)),
                ('highlight_2', models.CharField(blank=True, max_length=150, null=True)),
                ('highlight_3', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolutionFeatureArchitecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_1', models.CharField(blank=True, max_length=100, null=True)),
                ('badge_2', models.CharField(blank=True, max_length=100, null=True)),
                ('badge_3', models.CharField(blank=True, max_length=100, null=True)),
                ('bullet_1', models.CharField(blank=True, max_length=255, null=True)),
                ('bullet_2', models.CharField(blank=True, max_length=255, null=True)),
                ('bullet_3', models.CharField(blank=True, max_length=255, null=True)),
                ('bullet_4', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SolutionFeatureBTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_1', models.CharField(blank=True, max_length=100, null=True)),
                ('badge_2', models.CharField(blank=True, max_length=100, null=True)),
                ('badge_3', models.CharField(blank=True, max_length=100, null=True)),
                ('bullet_1', models.CharField(blank=True, max_length=255, null=True)),
                ('bullet_2', models.CharField(blank=True, max_length=255, null=True)),
                ('bullet_3', models.CharField(blank=True, max_length=255, null=True)),
                ('bullet_4', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
