# Generated by Django 5.2.8 on 2025-11-28 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_solutionaudiencecategory_solutioncta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('pricing', 'Page Tarifs'), ('home', 'Page Accueil'), ('features', 'Page Fonctionnalités')], max_length=20, unique=True, verbose_name='Page')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subtitle', models.TextField(verbose_name='Sous-titre')),
                ('primary_text', models.CharField(max_length=50, verbose_name='Texte bouton principal')),
                ('primary_url', models.URLField(verbose_name='URL bouton principal')),
                ('primary_icon', models.CharField(blank=True, help_text='Classe Bootstrap Icon', max_length=50, verbose_name='Icône bouton principal')),
                ('secondary_text', models.CharField(max_length=50, verbose_name='Texte bouton secondaire')),
                ('secondary_url', models.CharField(max_length=200, verbose_name='URL bouton secondaire')),
                ('secondary_icon', models.CharField(blank=True, max_length=50, verbose_name='Icône bouton secondaire')),
                ('highlight_1', models.CharField(max_length=50, verbose_name='Point de réassurance 1')),
                ('highlight_1_icon', models.CharField(default='bi bi-shield-lock', max_length=50, verbose_name='Icône point 1')),
                ('highlight_2', models.CharField(max_length=50, verbose_name='Point de réassurance 2')),
                ('highlight_2_icon', models.CharField(default='bi bi-credit-card-2-front-fill', max_length=50, verbose_name='Icône point 2')),
                ('highlight_3', models.CharField(max_length=50, verbose_name='Point de réassurance 3')),
                ('highlight_3_icon', models.CharField(default='bi bi-headset', max_length=50, verbose_name='Icône point 3')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Section CTA',
                'verbose_name_plural': 'Sections CTA',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('icon_class', models.CharField(default='bi bi-plus-circle', max_length=50, verbose_name="Classe d'icône Bootstrap")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question fréquente',
                'verbose_name_plural': 'Questions fréquentes',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('essentiel', 'Essentiel'), ('privilege', 'Privilège'), ('elite', 'Elite'), ('prestige', 'Prestige')], max_length=20, verbose_name='Type de formule')),
                ('period', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('biannual', 'Semestriel'), ('annual', 'Annuel')], max_length=20, verbose_name='Période de facturation')),
                ('price_eur', models.DecimalField(decimal_places=2, help_text='Prix par utilisateur', max_digits=10, verbose_name='Prix en EUR')),
                ('price_cfa', models.IntegerField(help_text='Prix par utilisateur', verbose_name='Prix en F CFA')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Plan mis en avant')),
                ('featured_badge', models.CharField(blank=True, help_text='Ex: ⭐ Le plus populaire', max_length=50, null=True, verbose_name='Badge du plan vedette')),
                ('action_url', models.URLField(default='https://app.aude.ci', verbose_name="URL d'action")),
                ('action_text', models.CharField(default='Choisir', max_length=50, verbose_name='Texte du bouton')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formule tarifaire',
                'verbose_name_plural': 'Formules tarifaires',
                'ordering': ['display_order', 'period'],
                'unique_together': {('plan_type', 'period')},
            },
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=200, verbose_name='Fonctionnalité')),
                ('is_bold', models.BooleanField(default=False, help_text="Ex: 'Tout l'Essentiel +'", verbose_name='Texte en gras')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('pricing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='website.pricingplan', verbose_name='Formule tarifaire')),
            ],
            options={
                'verbose_name': 'Fonctionnalité tarifaire',
                'verbose_name_plural': 'Fonctionnalités tarifaires',
                'ordering': ['pricing_plan', 'display_order'],
            },
        ),
    ]
