# Generated by Django 5.2.8 on 2025-12-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_ctasection_faq_pricingplan_pricingfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('position', models.CharField(max_length=100, verbose_name='Poste / Fonction')),
                ('company', models.CharField(max_length=100, verbose_name='Société')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo')),
                ('testimonial', models.TextField(verbose_name='Témoignage')),
                ('tags', models.CharField(blank=True, help_text='Séparez les mots-clés par des virgules', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-created_at'],
            },
        ),
    ]
