# Generated by Django 5.2.8 on 2025-12-01 16:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, help_text='Généré automatiquement depuis le nom', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description courte de la catégorie')),
                ('icone', models.CharField(blank=True, help_text='Classe Bootstrap Icons (ex: bi-lightbulb)', max_length=50)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = premier)")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du tag')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('couleur', models.CharField(default='#6366f1', help_text='Code hexadécimal (ex: #6366f1)', max_length=7)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text="Biographie courte de l'auteur")),
                ('photo', models.ImageField(blank=True, help_text='Photo de profil', null=True, upload_to='auteurs/')),
                ('poste', models.CharField(blank=True, help_text='Poste/titre (ex: Expert BTP Digital)', max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_auteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'article")),
                ('slug', models.SlugField(blank=True, help_text="URL de l'article (généré automatiquement)", max_length=220, unique=True)),
                ('resume', models.TextField(help_text='Résumé court pour les cartes (max 300 caractères)', max_length=300)),
                ('contenu', models.TextField(help_text="Contenu complet de l'article (Markdown supporté)")),
                ('image_couverture', models.ImageField(help_text='Image principale (recommandé: 1200x630px)', upload_to='blog/covers/%Y/%m/')),
                ('image_alt', models.CharField(blank=True, help_text="Texte alternatif pour l'accessibilité", max_length=200)),
                ('temps_lecture', models.IntegerField(default=5, help_text='Temps de lecture estimé (en minutes)')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=10)),
                ('vues', models.IntegerField(default=0, editable=False, help_text='Nombre de vues')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de publication visible')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, help_text='Description pour les moteurs de recherche (160 caractères max)', max_length=160)),
                ('en_vedette', models.BooleanField(default=False, help_text="Mettre en avant sur la page d'accueil")),
                ('autoriser_commentaires', models.BooleanField(default=True)),
                ('auteur', models.ForeignKey(editable=False, help_text='Auteur (défini automatiquement)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.auteur')),
                ('categorie', models.ForeignKey(help_text='Catégorie principale', on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='blog.categorie')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags multiples', related_name='articles', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication'],
                'indexes': [models.Index(fields=['-date_publication'], name='blog_articl_date_pu_587a62_idx'), models.Index(fields=['slug'], name='blog_articl_slug_cc8df7_idx'), models.Index(fields=['statut'], name='blog_articl_statut_3c1ce1_idx')],
            },
        ),
    ]
