# Generated by Django 5.2.8 on 2025-12-20 13:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text="Contenu complet de l'article (Markdown supporté)"),
        ),
    ]
